### ISSUE TITLE
runSTAR1pass fastq.gz is out of the scope of process working dir 

### ISSUE THREAD

**Issue by jaempawi** [compbiomed/RNA_Seq#4]
I ran across this error when trying out this pipeline:  Input tuple does not match input set cardinality declared by process `runSTAR1pass` -- offending value.

I have a TSV file that includes SAMPLE_ID, R1, and R2. I don't know how to fix this error as I am new to NextFlow. I would greatly appreciate any help!

**Comment by agower** [comment]
Hi Jenny, can you please share your Nextflow config and input files with me so that I can troubleshoot your issue?  You can email them to me at agower@bu.edu.  Thanks!

**Comment by jaempawi** [comment]
Hi Adam,
Thanks for replying. I figured out that my tsv file format was not working but I have fixed that yesterday However, seems like there is problem in generateBED step as shown below:
Homo_sapiens.GRCh38.108.ucsc.base_random.gtf.gz doesn't appear to be a GTF file

Would you be able to help me with this? Thanks.

Best,
Jenny Empawi
From: Adam C. Gower ***@***.***>
Date: Tuesday, February 14, 2023 at 10:20 PM
To: compbiomed/RNA_Seq ***@***.***>
Cc: Jenny Empawi ***@***.***>, State change ***@***.***>
Subject: Re: [compbiomed/RNA_Seq] runSTAR1pass fastq.gz is out of the scope of process working dir (Issue #4)

Hi Jenny, can you please share your Nextflow config and input files with me so that I can troubleshoot your issue? You can email them to me at ***@***.******@***.***>. Thanks!
